"""migrations

Revision ID: 0fb15a3e3e01
Revises: 1a660c242acb
Create Date: 2024-01-21 22:01:05.296638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb15a3e3e01'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
